-- Complete support taxonomy. Codes are stable API identifiers; names preserve
-- the category so the existing flat TicketType model remains backward compatible.
INSERT INTO `ticket_types` (`ispId`, `name`, `code`, `description`, `isActive`, `createdAt`, `updatedAt`)
SELECT isp.id, types.name, types.code, types.category, true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `ISP` isp
CROSS JOIN (
  SELECT 'New Connection / Coverage Check' name, 'NEW_CONNECTION_COVERAGE_CHECK' code, 'New Connection' category
  UNION ALL SELECT 'New Connection / Plan Inquiry', 'NEW_CONNECTION_PLAN_INQUIRY', 'New Connection'
  UNION ALL SELECT 'New Connection / New Installation', 'NEW_CONNECTION_NEW_INSTALLATION', 'New Connection'
  UNION ALL SELECT 'New Connection / Installation Reschedule', 'NEW_CONNECTION_INSTALLATION_RESCHEDULE', 'New Connection'
  UNION ALL SELECT 'New Connection / Activation Issue', 'NEW_CONNECTION_ACTIVATION_ISSUE', 'New Connection'
  UNION ALL SELECT 'Internet Connectivity / No Internet', 'CONNECTIVITY_NO_INTERNET', 'Internet Connectivity'
  UNION ALL SELECT 'Internet Connectivity / Slow Internet', 'CONNECTIVITY_SLOW_INTERNET', 'Internet Connectivity'
  UNION ALL SELECT 'Internet Connectivity / Frequent Disconnection', 'CONNECTIVITY_FREQUENT_DISCONNECTION', 'Internet Connectivity'
  UNION ALL SELECT 'Internet Connectivity / High Latency', 'CONNECTIVITY_HIGH_LATENCY', 'Internet Connectivity'
  UNION ALL SELECT 'Internet Connectivity / Packet Loss', 'CONNECTIVITY_PACKET_LOSS', 'Internet Connectivity'
  UNION ALL SELECT 'Internet Connectivity / Website or Application Not Working', 'CONNECTIVITY_APP_NOT_WORKING', 'Internet Connectivity'
  UNION ALL SELECT 'Wi-Fi Issue / Weak Signal', 'WIFI_WEAK_SIGNAL', 'Wi-Fi Issue'
  UNION ALL SELECT 'Wi-Fi Issue / Wi-Fi Not Connecting', 'WIFI_NOT_CONNECTING', 'Wi-Fi Issue'
  UNION ALL SELECT 'Wi-Fi Issue / Password Reset', 'WIFI_PASSWORD_RESET', 'Wi-Fi Issue'
  UNION ALL SELECT 'Wi-Fi Issue / Limited Coverage', 'WIFI_LIMITED_COVERAGE', 'Wi-Fi Issue'
  UNION ALL SELECT 'Wi-Fi Issue / Too Many Connected Devices', 'WIFI_TOO_MANY_DEVICES', 'Wi-Fi Issue'
  UNION ALL SELECT 'Fiber or Line Issue / LOS Red Light', 'FIBER_LOS_RED_LIGHT', 'Fiber/Line Issue'
  UNION ALL SELECT 'Fiber or Line Issue / Low Optical Power', 'FIBER_LOW_OPTICAL_POWER', 'Fiber/Line Issue'
  UNION ALL SELECT 'Fiber or Line Issue / Fiber Cable Damage', 'FIBER_CABLE_DAMAGE', 'Fiber/Line Issue'
  UNION ALL SELECT 'Fiber or Line Issue / Drop Cable Issue', 'FIBER_DROP_CABLE', 'Fiber/Line Issue'
  UNION ALL SELECT 'Fiber or Line Issue / Distribution Box Issue', 'FIBER_DISTRIBUTION_BOX', 'Fiber/Line Issue'
  UNION ALL SELECT 'Router or Device Issue / Router Not Powering On', 'DEVICE_NOT_POWERING_ON', 'Router/Device Issue'
  UNION ALL SELECT 'Router or Device Issue / Router Configuration', 'DEVICE_ROUTER_CONFIGURATION', 'Router/Device Issue'
  UNION ALL SELECT 'Router or Device Issue / Router Reset', 'DEVICE_ROUTER_RESET', 'Router/Device Issue'
  UNION ALL SELECT 'Router or Device Issue / Router Replacement', 'DEVICE_ROUTER_REPLACEMENT', 'Router/Device Issue'
  UNION ALL SELECT 'Router or Device Issue / ONU or ONT Issue', 'DEVICE_ONU_ONT', 'Router/Device Issue'
  UNION ALL SELECT 'Billing and Payment / Payment Not Updated', 'BILLING_PAYMENT_NOT_UPDATED', 'Billing and Payment'
  UNION ALL SELECT 'Billing and Payment / Incorrect Bill', 'BILLING_INCORRECT_BILL', 'Billing and Payment'
  UNION ALL SELECT 'Billing and Payment / Duplicate Payment', 'BILLING_DUPLICATE_PAYMENT', 'Billing and Payment'
  UNION ALL SELECT 'Billing and Payment / Invoice Request', 'BILLING_INVOICE_REQUEST', 'Billing and Payment'
  UNION ALL SELECT 'Billing and Payment / Receipt Request', 'BILLING_RECEIPT_REQUEST', 'Billing and Payment'
  UNION ALL SELECT 'Billing and Payment / Refund Request', 'BILLING_REFUND_REQUEST', 'Billing and Payment'
  UNION ALL SELECT 'Renewal / Package Renewal', 'RENEWAL_PACKAGE', 'Renewal'
  UNION ALL SELECT 'Renewal / Account Expired', 'RENEWAL_ACCOUNT_EXPIRED', 'Renewal'
  UNION ALL SELECT 'Renewal / Auto-Renewal Issue', 'RENEWAL_AUTO_ISSUE', 'Renewal'
  UNION ALL SELECT 'Renewal / Renewal Confirmation', 'RENEWAL_CONFIRMATION', 'Renewal'
  UNION ALL SELECT 'Package Change / Package Upgrade', 'PACKAGE_UPGRADE', 'Package Change'
  UNION ALL SELECT 'Package Change / Package Downgrade', 'PACKAGE_DOWNGRADE', 'Package Change'
  UNION ALL SELECT 'Package Change / Bandwidth Change', 'PACKAGE_BANDWIDTH_CHANGE', 'Package Change'
  UNION ALL SELECT 'Package Change / Package Information', 'PACKAGE_INFORMATION', 'Package Change'
  UNION ALL SELECT 'Package Change / Usage Inquiry', 'PACKAGE_USAGE_INQUIRY', 'Package Change'
  UNION ALL SELECT 'Account Management / Mobile Number Change', 'ACCOUNT_MOBILE_CHANGE', 'Account Management'
  UNION ALL SELECT 'Account Management / Email Change', 'ACCOUNT_EMAIL_CHANGE', 'Account Management'
  UNION ALL SELECT 'Account Management / Password Reset', 'ACCOUNT_PASSWORD_RESET', 'Account Management'
  UNION ALL SELECT 'Account Management / Ownership Transfer', 'ACCOUNT_OWNERSHIP_TRANSFER', 'Account Management'
  UNION ALL SELECT 'Account Management / Customer Details Update', 'ACCOUNT_CUSTOMER_DETAILS', 'Account Management'
  UNION ALL SELECT 'Relocation / Address Relocation', 'RELOCATION_ADDRESS', 'Relocation'
  UNION ALL SELECT 'Relocation / Internal Cable Relocation', 'RELOCATION_INTERNAL_CABLE', 'Relocation'
  UNION ALL SELECT 'Relocation / Router Relocation', 'RELOCATION_ROUTER', 'Relocation'
  UNION ALL SELECT 'Relocation / New Location Feasibility', 'RELOCATION_FEASIBILITY', 'Relocation'
  UNION ALL SELECT 'Suspension or Termination / Temporary Suspension', 'SUSPENSION_TEMPORARY', 'Suspension/Termination'
  UNION ALL SELECT 'Suspension or Termination / Service Reactivation', 'SUSPENSION_REACTIVATION', 'Suspension/Termination'
  UNION ALL SELECT 'Suspension or Termination / Permanent Termination', 'SUSPENSION_PERMANENT', 'Suspension/Termination'
  UNION ALL SELECT 'Suspension or Termination / Equipment Return', 'SUSPENSION_EQUIPMENT_RETURN', 'Suspension/Termination'
  UNION ALL SELECT 'Network Services / Public IP Request', 'NETWORK_PUBLIC_IP', 'Network Services'
  UNION ALL SELECT 'Network Services / Static IP Issue', 'NETWORK_STATIC_IP', 'Network Services'
  UNION ALL SELECT 'Network Services / Port Forwarding', 'NETWORK_PORT_FORWARDING', 'Network Services'
  UNION ALL SELECT 'Network Services / CGNAT Issue', 'NETWORK_CGNAT', 'Network Services'
  UNION ALL SELECT 'Network Services / DNS Issue', 'NETWORK_DNS', 'Network Services'
  UNION ALL SELECT 'Network Services / VPN Issue', 'NETWORK_VPN', 'Network Services'
  UNION ALL SELECT 'Network Services / CCTV or Gaming Issue', 'NETWORK_CCTV_GAMING', 'Network Services'
  UNION ALL SELECT 'IPTV or Value-Added Services / IPTV Not Working', 'VAS_IPTV_NOT_WORKING', 'IPTV/Value-Added Services'
  UNION ALL SELECT 'IPTV or Value-Added Services / Set-Top Box Issue', 'VAS_SET_TOP_BOX', 'IPTV/Value-Added Services'
  UNION ALL SELECT 'IPTV or Value-Added Services / Missing Channel', 'VAS_MISSING_CHANNEL', 'IPTV/Value-Added Services'
  UNION ALL SELECT 'IPTV or Value-Added Services / OTT Activation', 'VAS_OTT_ACTIVATION', 'IPTV/Value-Added Services'
  UNION ALL SELECT 'IPTV or Value-Added Services / Voice Service Issue', 'VAS_VOICE_SERVICE', 'IPTV/Value-Added Services'
  UNION ALL SELECT 'Outage / Area Outage', 'OUTAGE_AREA', 'Outage'
  UNION ALL SELECT 'Outage / Planned Maintenance', 'OUTAGE_PLANNED_MAINTENANCE', 'Outage'
  UNION ALL SELECT 'Outage / Backbone Issue', 'OUTAGE_BACKBONE', 'Outage'
  UNION ALL SELECT 'Outage / Upstream Issue', 'OUTAGE_UPSTREAM', 'Outage'
  UNION ALL SELECT 'Outage / Power Failure', 'OUTAGE_POWER_FAILURE', 'Outage'
  UNION ALL SELECT 'Complaint or Escalation / Technician Delay', 'COMPLAINT_TECHNICIAN_DELAY', 'Complaint/Escalation'
  UNION ALL SELECT 'Complaint or Escalation / Unresolved Issue', 'COMPLAINT_UNRESOLVED', 'Complaint/Escalation'
  UNION ALL SELECT 'Complaint or Escalation / Poor Customer Service', 'COMPLAINT_CUSTOMER_SERVICE', 'Complaint/Escalation'
  UNION ALL SELECT 'Complaint or Escalation / Installation Delay', 'COMPLAINT_INSTALLATION_DELAY', 'Complaint/Escalation'
  UNION ALL SELECT 'Complaint or Escalation / Billing Dispute', 'COMPLAINT_BILLING_DISPUTE', 'Complaint/Escalation'
  UNION ALL SELECT 'Complaint or Escalation / Supervisor Escalation', 'COMPLAINT_SUPERVISOR', 'Complaint/Escalation'
  UNION ALL SELECT 'Other', 'OTHER', 'Other'
) types
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `description` = VALUES(`description`), `isActive` = true, `updatedAt` = CURRENT_TIMESTAMP(3);
