services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: kashtrix-api
    restart: unless-stopped

    command: sh -c "npm run dockerStartup && npm start"

    ports:
      - "127.0.0.1:3200:3200"

    volumes:
      - ./uploads:/app/uploads

    env_file:
      - /etc/kashtrix/secrets/backend.env

    extra_hosts:
      - "host.docker.internal:172.20.0.1"

    networks:
      - app-network

networks:
  app-network:
    external: true
    name: kashtrix_backend_net
