const crypto=require('crypto');
const {getDeviceDefinition,capabilitiesFor}=require('./device-catalog');
const {normalizeDeviceResponse}=require('./device-response-normalizer.service');
class UnsupportedCapabilityError extends Error{constructor(capability){super(`Capability "${capability}" is not supported for this device, firmware, or communication method.`);this.code='UNSUPPORTED_CAPABILITY';this.status=400;}}
const rosMajor=device=>Number.parseInt(String(device.operatingSystemVersion||device.firmwareVersion||'0'),10)||0;
const junos=command=>`cli -c "${command} | no-more"`;
const MIKROTIK_COMMANDS={
 system:'/system resource print',health:'/system health print',interfaces:'/interface print','interfaces-live-traffic':'/interface monitor-traffic all once',traffic:'/interface monitor-traffic all once',routes:'/ip route print',configuration:'/export terse',
 'interfaces-ethernet':'/interface ethernet print','interfaces-bridges':'/interface bridge print','interfaces-bridge-ports':'/interface bridge port print','interfaces-vlan-interfaces':'/interface vlan print','interfaces-bonding':'/interface bonding print','interfaces-sfp-details':'/interface ethernet monitor all once',
 'ip-addresses':'/ip address print','ip-pools':'/ip pool print','ip-dhcp-server':'/ip dhcp-server print','ip-dhcp-client':'/ip dhcp-client print','ip-dns':'/ip dns print','ip-arp':'/ip arp print','ip-routes':'/ip route print',
 'routing-routing-tables':device=>rosMajor(device)>=7?'/routing table print':'/ip route print','routing-bgp':device=>rosMajor(device)>=7?'/routing bgp session print':'/routing bgp peer print','routing-ospf':'/routing ospf neighbor print','routing-filters':device=>rosMajor(device)>=7?'/routing filter rule print':'/routing filter print','routing-vrf':device=>rosMajor(device)>=7?'/ip vrf print':'/ip route vrf print',
 'ppp-profiles':'/ppp profile print','ppp-secrets':'/ppp secret print','ppp-active-sessions':'/ppp active print','ppp-pppoe-server':'/interface pppoe-server server print',
 'radius-servers':'/radius print','radius-incoming':'/radius incoming print','radius-status':'/radius monitor all once',
 'queues-simple-queues':'/queue simple print','queues-queue-trees':'/queue tree print','queues-queue-types':'/queue type print',
 'firewall-filter':'/ip firewall filter print','firewall-nat':'/ip firewall nat print','firewall-mangle':'/ip firewall mangle print','firewall-raw':'/ip firewall raw print','firewall-address-lists':'/ip firewall address-list print',
 'vpn-wireguard':'/interface wireguard print','vpn-ipsec':'/ip ipsec active-peers print','vpn-l2tp':'/interface l2tp-server server print','vpn-sstp':'/interface sstp-server server print','vpn-openvpn':'/interface ovpn-server server print',
 hotspot:'/ip hotspot print',services:'/ip service print',snmp:'/snmp print',
 'system-identity':'/system identity print','system-users':'/user print','system-clock':'/system clock print','system-ntp':'/system ntp client print','system-logging':'/system logging print','system-scripts':'/system script print','system-scheduler':'/system scheduler print','system-packages':'/system package print','system-routerboard':'/system routerboard print',
 diagnostics:'/tool profile once','configuration-backup':'/file print','configuration-restore':'/file print','configuration-export':'/export terse','configuration-history':'/system history print'
};
const COMMANDS={
 mikrotik:MIKROTIK_COMMANDS,
 cisco:{system:'show version',health:'show environment',interfaces:'show interfaces status','interfaces-counters':'show interfaces counters','interfaces-errors':'show interfaces counters errors',traffic:'show interfaces counters',vlans:'show vlan',routes:'show ip route','mac-table':'show mac address-table',trunks:'show interfaces trunk',stp:'show spanning-tree',lldp:'show lldp neighbors',configuration:'show running-config'},
 'huawei-olt':{system:'display version',health:'display temperature 0',chassis:'display board 0',boards:'display board 0',interfaces:'display board 0',uplinks:'display board 0/9','pon-ports':'display port state all',onus:'display ont info summary 0/0',vlans:'display vlan all',alarms:'display alarm active all list',logs:'display logbuffer',statistics:'display cpu 0/6',traffic:'display port traffic 0',configuration:'display current-configuration'},
 bdcom:{system:'show version',health:'show alarm',interfaces:'show interface brief',traffic:'show interface counters',configuration:'show running-config'},cdata:{system:'show version',health:'show alarm',interfaces:'show interface brief',traffic:'show interface counters',configuration:'show running-config'},vsol:{system:'show version',health:'show alarm',interfaces:'show interface brief',traffic:'show interface counters',configuration:'show running-config'},
 'nokia-olt':{system:'show system information',health:'show system alarms',chassis:'show chassis',boards:'show card',interfaces:'show port',traffic:'show port statistics',alarms:'show system alarms',logs:'show log log-id 99 count 100 descending',configuration:'admin display-config'},'nokia-bng':{system:'show system information',health:'show system alarms',chassis:'show chassis',cards:'show card',mdas:'show mda',ports:'show port',interfaces:'show port',lags:'show lag',optics:'show port detail',subscribers:'show service active-subscribers','subscribers-active-subscribers':'show service active-subscribers','subscribers-pppoe-sessions':'show service active-subscribers','subscribers-ipoe-sessions':'show service active-subscribers','subscribers-dhcp-sessions':'show service active-subscribers','subscribers-session-details':'show service active-subscribers hierarchy','authentication-radius-servers':'show router radius','services-vprn':'show service service-using vprn','services-ies':'show service service-using ies','services-vpls':'show service service-using vpls','services-epipe':'show service service-using epipe','routing-routes':'show router route-table','routing-routing-table':'show router route-table','routing-bgp':'show router bgp summary','routing-ospf':'show router ospf neighbor','routing-is-is':'show router isis adjacency','routing-static-routes':'show router static-route','routing-mpls':'show router mpls status','routing-ldp':'show router ldp status','routing-bfd':'show router bfd session',radius:'show router radius',alarms:'show system alarms',logs:'show log log-id 99 count 100 descending',cpu:'show system cpu',memory:'show system memory-pools',traffic:'show port statistics',routes:'show router route-table',routing:'show router route-table',configuration:'admin display-config'},
 'linux-server':{system:'uname -a; cat /etc/os-release 2>/dev/null; uptime',health:'uptime; free -m; df -P',cpu:'uptime; ps -eo pid,comm,%cpu --sort=-%cpu | head -n 11',memory:'free -m',disks:'df -P',filesystems:'df -PT',interfaces:'ip -brief address',traffic:'cat /proc/net/dev',addresses:'ip -brief address',routes:'ip route',neighbors:'ip neigh',dns:'cat /etc/resolv.conf',ports:'ss -lntup',processes:'ps -eo pid,user,comm,%cpu,%mem --sort=-%cpu',services:'systemctl --no-pager --plain --type=service --state=running',users:'getent passwd',groups:'getent group',packages:'dpkg-query -W 2>/dev/null',updates:'apt list --upgradable 2>/dev/null',configuration:'hostnamectl 2>/dev/null || hostname'},
 'fortiget-firewall':{system:d=>d.communicationMethod==='web_api'?'/api/v2/monitor/system/status':'get system status',health:d=>d.communicationMethod==='web_api'?'/api/v2/monitor/system/resource/usage':'get system performance status',interfaces:d=>d.communicationMethod==='web_api'?'/api/v2/cmdb/system/interface':'show system interface',zones:'show system zone','virtual-routers':'get router info routing-table all','static-routes':'show router static','dynamic-routing':'get router info routing-table all',dns:'show system dns',dhcp:'show system dhcp server','object-addresses':'show firewall address','address-groups':'show firewall addrgrp','custom-services':'show firewall service custom','service-groups':'show firewall service group',schedules:'show firewall schedule recurring',routes:d=>d.communicationMethod==='web_api'?'/api/v2/monitor/router/ipv4':'get router info routing-table all',policies:d=>d.communicationMethod==='web_api'?'/api/v2/cmdb/firewall/policy':'show firewall policy',nat:'show firewall policy',vpn:d=>d.communicationMethod==='web_api'?'/api/v2/monitor/vpn/ipsec':'get vpn ipsec tunnel summary',sessions:'diagnose sys session stat',traffic:d=>d.communicationMethod==='web_api'?'/api/v2/monitor/system/interface/select':'diagnose netlink interface list',alarms:'diagnose alertconsole list',logs:'execute log display',ha:'get system ha status',configuration:d=>d.communicationMethod==='web_api'?'/api/v2/cmdb/system/global':'show full-configuration'},'alto-palo':{system:'show system info',health:'show system resources',interfaces:'show interface all',traffic:'show counter interface all',routes:'show routing route',configuration:'show config running'},sophos:{system:'system diagnostics show version-info',health:'system diagnostics show system-health',interfaces:'system diagnostics show interfaces',traffic:'system diagnostics show interfaces',routes:'system diagnostics show routes',configuration:'show configuration'}
 ,'juniper-switch':{system:junos('show version'),health:junos('show chassis environment'),interfaces:junos('show interfaces terse'),'interfaces-counters':junos('show interfaces extensive'),'interfaces-errors':junos('show interfaces extensive | match "error|drop"'),traffic:junos('show interfaces statistics'),vlans:junos('show vlans'),'mac-table':junos('show ethernet-switching table'),stp:junos('show spanning-tree bridge'),lldp:junos('show lldp neighbors'),lacp:junos('show lacp interfaces'),routes:junos('show route summary'),'static-routes':junos('show route protocol static'),'routing-bgp':junos('show bgp summary'),'routing-ospf':junos('show ospf neighbor'),'routing-isis':junos('show isis adjacency'),'routing-vrf':junos('show route instance'),routing:junos('show route summary'),logs:junos('show log messages | last 100'),configuration:junos('show configuration | display set')}
 ,'juniper-bras':{system:junos('show version'),health:junos('show chassis environment'),interfaces:junos('show interfaces terse'),traffic:junos('show interfaces statistics'),subscribers:junos('show subscribers summary'),radius:junos('show network-access aaa statistics'),routes:junos('show route summary'),routing:junos('show route summary'),logs:junos('show log messages | last 100'),configuration:junos('show configuration | display set')}
};
const COMMAND_ALLOWLIST={'linux-server':[/^uname(?:\s|$)/i,/^uptime(?:\s|$)/i,/^free(?:\s|$)/i,/^df(?:\s|$)/i,/^ip\s+(?:address|addr|route|link|neighbor|neigh)(?:\s|$)/i,/^ss(?:\s|$)/i,/^ps(?:\s|$)/i,/^systemctl\s+status\s+[a-z0-9@_.-]+$/i,/^journalctl\s+(?:-n\s+\d+|--since\s+[^;&|]+)$/i,/^cat\s+\/(?:etc\/(?:os-release|resolv\.conf)|proc\/net\/dev)$/i],mikrotik:[/^\/(?:system|interface|ip|routing|radius|log|file|queue|ppp|snmp|tool)(?:\s+[a-z0-9_.-]+)*\s+(?:print|get|monitor|profile|monitor-traffic)(?:\s+[a-z0-9_.=*,:/@+-]+)*$/i],default:[/^(?:show|display|get)\s+[a-z0-9_./ +*|"-]+$/i]};
class BaseDeviceAdapter{
 constructor(device,connections){this.device=device;this.connections=connections;this.definition=getDeviceDefinition(device.deviceType);if(!this.definition)throw new UnsupportedCapabilityError(device.deviceType);}
 getCapabilities(){const base=capabilitiesFor(this.device.deviceType,this.device.communicationMethod,this.device.firmwareVersion),known=new Map(base.map(item=>[item.capability,item]));for(const capability of Object.keys(COMMANDS[this.device.deviceType]||{}))known.set(capability,{capability,supported:true,readOnly:true,metadata:{verifiedReadCommand:true}});return[...known.values()];}
 commandFor(module){const commands=COMMANDS[this.device.deviceType]||{},normalized=module==='dashboard'?'system':module==='routing'?'routes':module,direct=commands[normalized],fallback=['log','logs'].includes(module)?commands.health:null,spec=direct??fallback,command=typeof spec==='function'?spec(this.device):spec;if(!command)throw new UnsupportedCapabilityError(module);return command;}
 async testConnection(){const result=await this.getSystemInfo();return{connected:true,method:result.meta?.protocol||this.device.communicationMethod,protocol:result.meta?.protocol,latencyMs:result.meta?.durationMs||0,summary:JSON.stringify(result.view||{}).slice(0,1000),profile:result.profile,profilesAttempted:result.profilesAttempted,legacyCompatibilityUsed:result.legacyCompatibilityUsed,diagnostics:result.diagnostics};}
 protocolFor(module){const preferred=String(this.device.preferredProtocol||'AUTO').toUpperCase(),fallbacks=Array.isArray(this.device.fallbackProtocols)?this.device.fallbackProtocols.map(value=>String(value).toUpperCase()):[],snmpConfigured=preferred==='SNMP'||fallbacks.includes('SNMP'),normalized=String(module).toLowerCase(),systemResource=['system','dashboard','health','cpu','memory','resource-usage'].includes(normalized),sshVerified=String(this.device.lastSuccessfulProtocol||'').toUpperCase()==='SSH',telemetry=new Set(['system','dashboard','health','cpu','memory','resource-usage','boards','cards','mdas','chassis','entity-inventory','hardware-inventory','interfaces','interfaces-counters','interfaces-live-traffic','traffic','optics','sfp-details','routes','routing','routing-routes','routing-routing-table','static-routes']);if(systemResource&&preferred==='SSH'&&sshVerified)return'SSH';if(snmpConfigured&&telemetry.has(normalized))return'SNMP';if(preferred==='SNMP')return fallbacks.find(protocol=>protocol!=='SNMP')||'SNMP';return preferred;}
 async read(module='system',context={}){const requestedProtocol=this.protocolFor(module),command=requestedProtocol==='SNMP'?module:this.commandFor(module),execution=await this.connections.execute(this.device,command,{...context,module,requestedProtocol}),normalized=normalizeDeviceResponse({device:this.device,module,command,data:execution.result,durationMs:execution.durationMs,protocol:execution.protocol});return{...normalized,sessionId:execution.sessionId,profile:execution.profile,profilesAttempted:execution.profilesAttempted,legacyCompatibilityUsed:execution.legacyCompatibilityUsed,diagnostics:execution.diagnostics};}
 async getSystemInfo(){return this.read('system');}async getHealth(){return this.read('health');}async getInterfaces(){return this.read('interfaces');}async getRoutes(){return this.read('routes');}async getConfiguration(){return this.read('configuration');}
 async executeReadCommand(command){if(!command||/[;&|`$<>\n\r]/.test(command))throw Object.assign(new Error('Command contains unsupported shell control characters.'),{status:400,code:'INVALID_COMMAND'});const allowed=COMMAND_ALLOWLIST[this.device.deviceType]||COMMAND_ALLOWLIST.default;if(!allowed.some(pattern=>pattern.test(command.trim())))throw Object.assign(new Error('This terminal accepts only audited read-only commands for the selected device type.'),{status:403,code:'COMMAND_NOT_ALLOWED'});const prepared=['juniper-switch','juniper-bras'].includes(this.device.deviceType)?junos(command.trim()):command.trim();return this.connections.execute(this.device,prepared);}
 async executeConfigurationCommand(){throw new UnsupportedCapabilityError('configuration-write');}
 async createBackup(){const configuration=await this.getConfiguration(),content=typeof configuration.data==='string'?configuration.data:JSON.stringify(configuration.data??configuration.view??configuration,null,2);return{content,format:'text',hash:crypto.createHash('sha256').update(content).digest('hex')};}
 async restoreBackup(){throw new UnsupportedCapabilityError('backup-restore');}disconnect(){}
}
class MikrotikAdapter extends BaseDeviceAdapter{async getSystemInfo(){const result=await super.getSystemInfo(),records=result.view?.items||[],text=records.map(item=>item.message||'').join('\n'),version=records[0]?.version||result.view?.fields?.Version||text.match(/version:\s*([^\s]+)/i)?.[1]||this.device.operatingSystemVersion||this.device.firmwareVersion;return{...result,routerOsMajor:Number(String(version||'').split('.')[0])||null,firmwareVersion:version||null};}}
class LinuxAdapter extends BaseDeviceAdapter{}
class HuaweiOltAdapter extends BaseDeviceAdapter{
 async read(module='system',context={}){
  if(module==='health'){
   const execution=await this.connections.withConnection(this.device,async(connection,method)=>{
    if(method==='SNMP')return connection.getModule('health');
    return connection.runShellSession(async send=>{
     const output=[];
     for(const slot of ['0/6','0/7'])output.push(`KASHTRIX_CPU_SLOT ${slot}\n${await send(`display cpu ${slot}`,500)}`);
     output.push(await send('display temperature 0',500));
     return output.join('\n');
    });
   },null,{...context,requestedProtocol:this.protocolFor(module),module});
   const normalized=normalizeDeviceResponse({device:this.device,module,command:'Huawei live resource bundle',data:execution.result,durationMs:execution.durationMs,protocol:execution.protocol});
   return{...normalized,sessionId:execution.sessionId,profile:execution.profile,profilesAttempted:execution.profilesAttempted,legacyCompatibilityUsed:execution.legacyCompatibilityUsed,diagnostics:execution.diagnostics};
  }
  if(module!=='pon-ports')return super.read(module,context);
  const boards=await super.read('boards');
  const gpon=(boards.view?.items||[]).filter(row=>/GP|PON/i.test(String(row.boardName||''))).map(row=>Number(row.slot)).filter(Number.isInteger);
  const slots=[...new Set(gpon.length?gpon:[0])].slice(0,18);
  const execution=await this.connections.withConnection(this.device,async(connection,method)=>{
   if(method!=='SSH'){
    const sshPort=Number(this.device.connectionProfile?.sshPort||this.device.managementPort||22);
    const preferredProtocol=String(this.device.preferredProtocol||'AUTO').toUpperCase();
    const fallbacks=Array.isArray(this.device.fallbackProtocols)?this.device.fallbackProtocols.map(String).map(p=>p.toUpperCase()):[];
    const canUseSsh=preferredProtocol==='SSH'||preferredProtocol==='AUTO'||fallbacks.includes('SSH');
    throw Object.assign(new Error(`Huawei OLT PON port discovery requires SSH protocol. Current: ${method}. Configured: ${preferredProtocol}. Device SSH available at ${this.device.host}:${sshPort}. ${canUseSsh?'SSH is available - check device connectivity.':'SSH not configured - update device connection profile to use SSH or AUTO mode.'}`),{code:'DEVICE_PROTOCOL_UNSUPPORTED',status:400,device:this.device.id,protocol:method,required:'SSH'});
   }
   return connection.runShellSession(async send=>{
    const outputs=[];
    await send('config');
    for(const slot of slots){
     const enter=await send(`interface gpon 0/${slot}`);
     const ports=await send('display port state all',Math.min(3000,Math.max(800,Number(this.device.commandTimeout||15000)/8)));
     const leave=await send('quit');
     outputs.push(`KASHTRIX_SLOT 0/${slot}\n${enter}\n${ports}\n${leave}`);
    }
    await send('quit');
    return outputs.join('\n');
   });
  },null,{...context,requestedProtocol:'SSH',module});
  const normalized=normalizeDeviceResponse({device:this.device,module,command:'display port state all',data:execution.result,durationMs:execution.durationMs,protocol:execution.protocol});
  return{...normalized,sessionId:execution.sessionId,profile:execution.profile,profilesAttempted:execution.profilesAttempted,legacyCompatibilityUsed:execution.legacyCompatibilityUsed,diagnostics:execution.diagnostics};
 }
}
const createAdapter=(device,connections)=>device.deviceType==='mikrotik'?new MikrotikAdapter(device,connections):device.deviceType==='linux-server'?new LinuxAdapter(device,connections):device.deviceType==='huawei-olt'?new HuaweiOltAdapter(device,connections):new BaseDeviceAdapter(device,connections);
module.exports={BaseDeviceAdapter,MikrotikAdapter,LinuxAdapter,HuaweiOltAdapter,UnsupportedCapabilityError,createAdapter,COMMANDS,COMMAND_ALLOWLIST};
