const parserRegistry=require('./device-parsers/ParserRegistry');
const PROMPT=/^(?:\[[^\]]+\]|[\w().@:/-]+)?[>#\$%]\s*$/;
const STRUCTURED_MODULE=/(?:interface|vlan|card|board|service|route|subscriber|session|ont|onu|pon|port|mda|lag|optic|firewall|polic|traffic|resource|system|health|alarm|hardware|chassis|radius|dhcp|queue|address|neighbor|process|disk|filesystem|package|user|group|vpn|nat)/i;
function unwrap(value){let current=value;while(Array.isArray(current)&&current.length===1)current=current[0];return current;}
function cleanKey(key){return String(key||'').replace(/^\./,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function bool(value){return value===true||['true','yes','1'].includes(String(value).toLowerCase());}
function stripCli(value,command=''){return String(value||'').replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g,'').replace(/\r/g,'').split('\n').map(line=>line.replace(/---- More \( Press 'Q' to break \) ----\s*/ig,'').replace(/Press any key to continue\s*\(Q to quit\)\s*/ig,'').replace(/--More--\s*/ig,'').trimEnd()).filter(line=>{const trimmed=line.trim();if(!trimmed||PROMPT.test(trimmed))return false;if(/^(?:user ?name|login|password)\s*:/i.test(trimmed))return false;if(/^(?:--more--|---- more|press any key to continue)/i.test(trimmed))return false;if(/^Command is being executed/i.test(trimmed))return false;if(command&&(trimmed===command||trimmed.endsWith(`#${command}`)||trimmed.endsWith(`>${command}`)||trimmed.endsWith(`% ${command}`)))return false;return true;});}
function summarize(items){const status=item=>String(item.state??item.status??item.link??item.operState??item.admin??item.running??item.disabled??'').toLowerCase();return{total:items.length,up:items.filter(item=>/^(up|running|active|true|online)$/.test(status(item))).length,down:items.filter(item=>/^(down|stopped|inactive|false|offline)$/.test(status(item))).length,disabled:items.filter(item=>bool(item.disabled)).length,dynamic:items.filter(item=>bool(item.dynamic)).length,invalid:items.filter(item=>bool(item.invalid)).length};}
function normalizeObjects(value,module=''){const rows=(Array.isArray(value)?value:[value]).filter(item=>item&&typeof item==='object'&&!Array.isArray(item)).map(item=>Object.fromEntries(Object.entries(item).map(([key,val])=>[key.replace(/^\./,''),val]))),traffic=['traffic','interfaces-live-traffic'].includes(module),rate=(row,direction)=>Number(String(row[`${direction}-bits-per-second`]??row[`${direction}BitsPerSecond`]??0).replaceAll(',',''))||0,summary=traffic?{total:rows.length,active:rows.filter(row=>rate(row,'rx')>0||rate(row,'tx')>0).length,rxBitsPerSecond:rows.reduce((total,row)=>total+rate(row,'rx'),0),txBitsPerSecond:rows.reduce((total,row)=>total+rate(row,'tx'),0)}:summarize(rows);return{kind:'table',columns:[...new Set(rows.flatMap(row=>Object.keys(row)))].slice(0,24),items:rows,summary};}
function parseCiscoInterfaces(lines){const items=[];for(const line of lines){const match=line.match(/^((?:gi|te|fa|xe|ge|eth|po)\S*)\s+(\S+)\s+(Full|Half|--)\s+(\d+|--)\s+(\S+)\s+(\S+)\s+(Up|Down|Not Present)\s*(.*)$/i);if(match)items.push({port:match[1],type:match[2],duplex:match[3],speed:match[4],negotiation:match[5],flowControl:match[6],state:match[7],details:match[8].trim()||null});}return items;}
function parseCiscoVlans(lines){const items=[];for(const line of lines){const match=line.match(/^\s*(\d+)\s+(\S+)\s+(.*?)\s{2,}(.*?)\s{2,}([DSGRV])\s*$/);if(match)items.push({vlanId:Number(match[1]),name:match[2],taggedPorts:match[3].trim(),untaggedPorts:match[4].trim(),createdBy:match[5]});}return items;}
function parseJunosInterfaces(lines){const items=[];for(const line of lines){const match=line.match(/^(\S+)\s+(up|down)\s+(up|down)(?:\s+(\S+))?(?:\s+(.*))?$/i);if(match)items.push({interface:match[1],admin:match[2],link:match[3],protocol:match[4]||null,addressOrRemote:match[5]?.trim()||null});}return items;}
function parseJunosMacTable(lines){const items=[];for(const line of lines){const match=line.match(/^\s*(\S+)\s+([0-9a-f:.-]{12,17})\s+(?:Learn|Static|Dynamic|D|S)\S*\s+\S*\s+(\S+)/i);if(match)items.push({vlan:match[1],macAddress:match[2],interface:match[3]});}return items;}
function parseHuaweiBoards(lines){const items=[];for(const line of lines){const match=line.match(/^\s*(\d+)\s+(H\w+)\s+(\w+(?:_\w+)?)\s*$/i);if(match)items.push({slot:Number(match[1]),boardName:match[2],status:match[3]});}return items;}
function parseHuaweiPonPorts(lines){const items=[];let slot='0/0',current=null;const finish=()=>{if(current?.port!==undefined){current.fsp=current.fsp||`${slot}/${current.port}`;items.push(current);}current=null;};for(const raw of lines){const line=raw.trim();const marker=line.match(/^KASHTRIX_SLOT\s+(\d+\/\d+)/i);if(marker){finish();slot=marker[1];continue;}const fsp=line.match(/^(?:F\/?S\/?P|Frame\/?Slot\/?Port)\s*[: ]+\s*(\d+\/\d+\/(\d+))/i);if(fsp){finish();current={fsp:fsp[1],frame:Number(fsp[1].split('/')[0]),slot:Number(fsp[1].split('/')[1]),port:Number(fsp[2])};continue;}const port=line.match(/^(?:Port(?:\s+ID)?|PON port)\s*[: ]+\s*(\d+)\s*$/i);if(port){finish();current={slot:Number(slot.split('/')[1]),frame:Number(slot.split('/')[0]),port:Number(port[1]),fsp:`${slot}/${port[1]}`};continue;}const row=line.match(/^(\d+)\s+(online|offline|up|down|normal|abnormal)\s+(on|off|up|down|enable|disable)(?:\s+(.*))?$/i);if(row){finish();current={slot:Number(slot.split('/')[1]),frame:Number(slot.split('/')[0]),port:Number(row[1]),fsp:`${slot}/${row[1]}`,portState:row[2],laserState:row[3],details:row[4]||null};finish();continue;}if(!current)continue;const kv=line.match(/^(.{2,48}?)\s{2,}(.+?)$/);if(!kv)continue;const key=kv[1].trim().toLowerCase(),value=kv[2].trim();if(/port state|link state/.test(key))current.portState=value;else if(/admin state/.test(key))current.adminState=value;else if(/laser state/.test(key))current.laserState=value;else if(/tx power/.test(key))current.txPowerDbm=Number(value.match(/-?\d+(?:\.\d+)?/)?.[0]);else if(/rx power/.test(key))current.rxPowerDbm=Number(value.match(/-?\d+(?:\.\d+)?/)?.[0]);else if(/temperature/.test(key))current.temperatureC=Number(value.match(/-?\d+(?:\.\d+)?/)?.[0]);else if(/voltage/.test(key))current.voltageV=Number(value.match(/-?\d+(?:\.\d+)?/)?.[0]);else if(/bias current/.test(key))current.biasCurrentMa=Number(value.match(/-?\d+(?:\.\d+)?/)?.[0]);else if(/ont.*(?:online|registered)/.test(key))current.onlineOnts=Number(value.match(/\d+/)?.[0]);else if(/ont.*(?:total|configured)/.test(key))current.totalOnts=Number(value.match(/\d+/)?.[0]);else if(/autofind/.test(key))current.autoFind=value;else if(/max distance/.test(key))current.maxDistanceKm=Number(value.match(/\d+(?:\.\d+)?/)?.[0]);}finish();return items;}
function parseHuaweiOntSummary(lines){const records=new Map();let port=null,section=null;for(const line of lines){const portMatch=line.match(/^\s*In port\s+(\d+\/\d+\/\d+)/i);if(portMatch){port=portMatch[1];section=null;continue;}if(/ONT\s+Run\s+Last/i.test(line)){section='state';continue;}if(/ONT\s+SN\s+Type/i.test(line)){section='details';continue;}if(!port)continue;if(section==='state'){const row=line.match(/^\s*(\d+)\s+(online|offline)\s+(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}|-)\s+(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}|-)\s+(\S.*)$/i);if(row){const key=`${port}:${row[1]}`;records.set(key,{...(records.get(key)||{}),port,ontId:Number(row[1]),runState:row[2].toLowerCase(),lastUpTime:row[3],lastDownTime:row[4],lastDownCause:row[5].trim()});}}else if(section==='details'){const row=line.match(/^\s*(\d+)\s+([0-9a-f]{16})\s+(\S+)\s+(\S+)\s+(\S+)\s+(.*)$/i);if(row){const key=`${port}:${row[1]}`;records.set(key,{...(records.get(key)||{}),port,ontId:Number(row[1]),serialNumber:row[2],type:row[3],distanceMeters:row[4],rxTxPowerDbm:row[5],description:row[6].trim()});}}}return[...records.values()];}
function parseHuaweiSystem(lines){const text=lines.join('\n'),version=text.match(/^\s*VERSION\s*:\s*(.+)$/mi)?.[1]?.trim(),patch=text.match(/^\s*PATCH\s*:\s*(.+)$/mi)?.[1]?.trim(),product=text.match(/^\s*PRODUCT\s*:\s*(.+)$/mi)?.[1]?.trim(),uptime=text.match(/Uptime is\s+(.+?)\s*$/mi)?.[1]?.trim();if(!version&&!product&&!uptime)return null;const fields=Object.fromEntries([['Product',product],['Software Version',version],['Patch',patch],['Uptime',uptime]].filter(([,value])=>value));return{kind:'key-value',fields,summary:{fields:Object.keys(fields).length}};}
function parseHuaweiHealth(lines){const cpus=[],temperatures=[];let slot=null;for(const raw of lines){const line=raw.trim(),marker=line.match(/^KASHTRIX_CPU_SLOT\s+(\d+\/\d+)/i);if(marker){slot=marker[1];continue;}const cpu=line.match(/CPU occupancy\s*:\s*(\d+(?:\.\d+)?)%/i);if(cpu)cpus.push({slot:slot||`board-${cpus.length+1}`,value:Number(cpu[1])});const temperature=line.match(/SlotID:\s*(\d+)\s+BoardName:\s*(\S+)\s+Temperature:\s*(-?\d+(?:\.\d+)?)C/i);if(temperature)temperatures.push({slot:temperature[1],board:temperature[2],value:Number(temperature[3])});}if(!cpus.length&&!temperatures.length)return null;const fields={};for(const row of cpus)fields[`CPU ${row.slot}`]=`${row.value}%`;for(const row of temperatures)fields[`Temperature slot ${row.slot} (${row.board})`]=`${row.value} C`;fields['CPU Load']=cpus.length?Math.max(...cpus.map(row=>row.value)):null;fields['Maximum Temperature']=temperatures.length?Math.max(...temperatures.map(row=>row.value)):null;return{kind:'key-value',fields,summary:{cpuLoadPercent:fields['CPU Load'],maximumTemperatureC:fields['Maximum Temperature'],cpuBoards:cpus.length,temperatureSensors:temperatures.length}};}
function parseNokiaPorts(lines){const items=[],connectors=new Map();let pending=null;for(const raw of lines){const line=raw.trim();if(!line||/^[=-]{5,}$/.test(line)||/^(?:Ports on|Port\s+Admin|Id\s+State)/i.test(line))continue;const child=line.match(/^(\S+)\s+(Up|Down)\s+(Yes|No)\s+(Up|Down)\s+(\d+|-)\s+(\d+|-)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)(?:\s+(.*))?$/i);if(child){const portId=child[1],parent=portId.includes('/c')&&portId.split('/').length===4?portId.replace(/\/\d+$/,''):null,connector=parent?connectors.get(parent):null;items.push({portId,parentConnector:parent,adminState:child[2],linkState:child[3],operState:child[4],configuredMtu:child[5]==='-'?null:Number(child[5]),operationalMtu:child[6]==='-'?null:Number(child[6]),lagId:child[7]==='-'?null:child[7],mode:child[8],encapsulation:child[9],type:child[10],transceiver:connector?.transceiver||child[11]?.trim()||null});pending=null;continue;}const connector=line.match(/^(\S+)\s+(Up|Down)\s+(?:Link\s+)?(Up|Down)\s+conn(?:\s+(\S+))?/i);if(connector){const row={portId:connector[1],parentConnector:null,adminState:connector[2],linkState:connector[3],operState:connector[3],configuredMtu:null,operationalMtu:null,lagId:null,mode:'connector',encapsulation:null,type:'connector',transceiver:connector[4]||null};connectors.set(row.portId,row);items.push(row);pending=null;continue;}if(/^\S+(?:\/\S+)+$/.test(line)){pending=line;continue;}if(pending){const wrapped=line.match(/^(Up|Down)\s+(Yes|No)\s+(Up|Down)\s+(\d+|-)\s+(\d+|-)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/i);if(wrapped){items.push({portId:pending,parentConnector:null,adminState:wrapped[1],linkState:wrapped[2],operState:wrapped[3],configuredMtu:wrapped[4]==='-'?null:Number(wrapped[4]),operationalMtu:wrapped[5]==='-'?null:Number(wrapped[5]),lagId:wrapped[6]==='-'?null:wrapped[6],mode:wrapped[7],encapsulation:wrapped[8],type:wrapped[9],transceiver:null});pending=null;}}}return items;}
function maskToPrefix(mask){const parts=String(mask||'').split('.').map(Number);if(parts.length!==4)return null;const bits=parts.map(part=>part.toString(2).padStart(8,'0')).join('');return /^1*0*$/.test(bits)?bits.indexOf('0')<0?32:bits.indexOf('0'):null;}
function parseFortigateInterfaces(lines){const items=[];let current=null,nested=0;const finish=()=>{if(current){items.push(current);current=null;nested=0;}};for(const raw of lines){const line=raw.trim(),edit=line.match(/^edit\s+"?([^"\s]+)"?/i);if(edit&&nested===0){finish();current={name:edit[1],vdom:'root',mode:'static',status:'up'};continue;}if(!current)continue;if(/^config\s+/i.test(line)){nested++;continue;}if(/^end$/i.test(line)){if(nested>0)nested--;continue;}if(/^next$/i.test(line)){finish();continue;}const set=line.match(/^set\s+(\S+)\s+(.+)$/i);if(!set)continue;const key=set[1].toLowerCase(),value=set[2].replace(/^"|"$/g,'');if(key==='ip'){const[address,mask]=value.split(/\s+/),prefix=maskToPrefix(mask);current.address=prefix===null?value:`${address}/${prefix}`;}else if(key==='allowaccess')current.allowAccess=value.split(/\s+/);else if(key==='snmp-index')current.snmpIndex=Number(value);else if(['vdom','alias','role','mode','type','status'].includes(key))current[key]=value;else current[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;}finish();return items;}
function parseTraffic(lines,deviceType){
 const items=[];
 if(deviceType==='linux-server'){for(const line of lines){const row=line.match(/^\s*([^:|]+):\s*(\d+)\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+)/);if(row)items.push({name:row[1].trim(),rxBytes:Number(row[2]),txBytes:Number(row[3])});}return items;}
 let current=null;const finish=()=>{if(current&&(current.rxBytes!==undefined||current.txBytes!==undefined||current.rxBitsPerSecond!==undefined||current.txBitsPerSecond!==undefined))items.push(current);current=null;};
 for(const line of lines){
  const junos=line.match(/^Physical interface:\s*([^,]+).*Physical link is\s+(Up|Down)/i);if(junos){finish();current={name:junos[1],state:junos[2]};continue;}
  const input=line.match(/^\s*Input bytes\s*:\s*(\d+)(?:\s+(\d+)\s+bps)?/i);if(input&&current){current.rxBytes=Number(input[1]);if(input[2])current.rxBitsPerSecond=Number(input[2]);continue;}
  const output=line.match(/^\s*Output bytes\s*:\s*(\d+)(?:\s+(\d+)\s+bps)?/i);if(output&&current){current.txBytes=Number(output[1]);if(output[2])current.txBitsPerSecond=Number(output[2]);continue;}
  const forti=line.match(/^if=([^\s]+).*\blink=(\d+)/i);if(forti){finish();current={name:forti[1],state:forti[2]==='0'?'up':'down'};continue;}
  const stats=line.match(/\brxb=(\d+).*\btxb=(\d+)/i);if(stats&&current){current.rxBytes=Number(stats[1]);current.txBytes=Number(stats[2]);continue;}
 }
 finish();if(items.length)return items;
 const headerIndex=lines.findIndex(line=>/\b(?:port|interface|name)\b/i.test(line)&&/\b(?:in|rx)[- ]?(?:octets|bytes|bits)/i.test(line)&&/\b(?:out|tx)[- ]?(?:octets|bytes|bits)/i.test(line));
 if(headerIndex>=0){const headers=lines[headerIndex].trim().split(/\s+/),nameIndex=headers.findIndex(value=>/^(?:port|interface|name)$/i.test(value)),rxIndex=headers.findIndex(value=>/^(?:in|rx)[-]?(?:octets|bytes|bits)$/i.test(value)),txIndex=headers.findIndex(value=>/^(?:out|tx)[-]?(?:octets|bytes|bits)$/i.test(value));for(const line of lines.slice(headerIndex+1)){const values=line.trim().split(/\s+/);if(nameIndex<0||rxIndex<0||txIndex<0||values.length<=Math.max(nameIndex,rxIndex,txIndex)||!/^[\d,]+$/.test(values[rxIndex])||!/^[\d,]+$/.test(values[txIndex]))continue;items.push({name:values[nameIndex],rxBytes:Number(values[rxIndex].replaceAll(',','')),txBytes:Number(values[txIndex].replaceAll(',',''))});}}
 return items;
}
function parseDelimitedTable(lines){const divider=lines.findIndex(line=>/^\s*[-=]{3,}(?:\s+[-=]{2,})+\s*$/.test(line));if(divider<1)return null;const headers=lines[divider-1].trim().split(/\s{2,}/).map(cleanKey),items=[];for(const line of lines.slice(divider+1)){if(!line.trim()||PROMPT.test(line.trim()))continue;const values=line.trim().split(/\s{2,}/);if(values.length<2)continue;items.push(Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])));}return items.length?items:null;}
function parseKeyValues(lines){const fields={};for(const line of lines){const match=line.match(/^\s*([^:=]{2,40})\s*[:=]\s*(.+?)\s*$/);if(match&&!/password|secret|community|token/i.test(match[1]))fields[cleanKey(match[1])]=match[2];}return fields;}
function normalizeCli(value,{device,module,command}){const lines=stripCli(value,command),joined=lines.join('\n'),registered=parserRegistry.parse({device,module,lines}),huaweiSystem=device.deviceType==='huawei-olt'&&module==='system'?parseHuaweiSystem(lines):null,huaweiHealth=device.deviceType==='huawei-olt'&&module==='health'?parseHuaweiHealth(lines):null,traffic=module==='traffic'?parseTraffic(lines,device.deviceType):[],interfaces=device.deviceType==='cisco'&&/interfaces/.test(module)?parseCiscoInterfaces(lines):[],vlans=device.deviceType==='cisco'&&/vlan/.test(module)?parseCiscoVlans(lines):[],junosInterfaces=/^juniper-/.test(device.deviceType)&&module==='interfaces'?parseJunosInterfaces(lines):[],junosMac=/^juniper-/.test(device.deviceType)&&module==='mac-table'?parseJunosMacTable(lines):[],huaweiBoards=device.deviceType==='huawei-olt'&&['boards','interfaces','uplinks'].includes(module)?parseHuaweiBoards(lines):[],huaweiPonPorts=device.deviceType==='huawei-olt'&&module==='pon-ports'?parseHuaweiPonPorts(lines):[],huaweiOnts=device.deviceType==='huawei-olt'&&module==='onus'?parseHuaweiOntSummary(lines):[],nokiaPorts=/^nokia-/.test(device.deviceType)&&['interfaces','ports'].includes(module)?parseNokiaPorts(lines):[],fortigateInterfaces=device.deviceType==='fortiget-firewall'&&module==='interfaces'?parseFortigateInterfaces(lines):[];
 if(registered)return{kind:'table',columns:registered.columns,items:registered.items,summary:registered.summary,entityType:registered.entityType,capabilityKey:registered.capabilityKey,parser:registered.parser,confidence:registered.confidence,warnings:registered.warnings};if(huaweiSystem)return huaweiSystem;if(huaweiHealth)return huaweiHealth;if(traffic.length)return{kind:'table',columns:Object.keys(traffic[0]),items:traffic,summary:{total:traffic.length}};if(interfaces.length)return{kind:'table',columns:Object.keys(interfaces[0]),items:interfaces,summary:summarize(interfaces)};if(vlans.length)return{kind:'table',columns:Object.keys(vlans[0]),items:vlans,summary:{total:vlans.length}};if(junosInterfaces.length)return{kind:'table',columns:Object.keys(junosInterfaces[0]),items:junosInterfaces,summary:summarize(junosInterfaces)};if(junosMac.length)return{kind:'table',columns:Object.keys(junosMac[0]),items:junosMac,summary:{total:junosMac.length}};if(huaweiBoards.length)return{kind:'table',columns:Object.keys(huaweiBoards[0]),items:huaweiBoards,summary:{total:huaweiBoards.length,normal:huaweiBoards.filter(row=>/normal/i.test(row.status)).length}};if(huaweiPonPorts.length)return{kind:'table',columns:[...new Set(huaweiPonPorts.flatMap(row=>Object.keys(row)))],items:huaweiPonPorts,summary:{total:huaweiPonPorts.length,up:huaweiPonPorts.filter(row=>/up|online|normal/i.test(String(row.portState))).length,down:huaweiPonPorts.filter(row=>/down|offline|abnormal/i.test(String(row.portState))).length,laserOn:huaweiPonPorts.filter(row=>/on|enable/i.test(String(row.laserState))).length}};if(huaweiOnts.length)return{kind:'table',columns:Object.keys(huaweiOnts[0]),items:huaweiOnts,summary:{total:huaweiOnts.length,online:huaweiOnts.filter(row=>row.runState==='online').length,offline:huaweiOnts.filter(row=>row.runState==='offline').length}};if(nokiaPorts.length)return{kind:'table',columns:Object.keys(nokiaPorts[0]),items:nokiaPorts,summary:{total:nokiaPorts.length,up:nokiaPorts.filter(row=>String(row.operState).toLowerCase()==='up').length,down:nokiaPorts.filter(row=>String(row.operState).toLowerCase()==='down').length,connectors:nokiaPorts.filter(row=>row.type==='connector').length}};if(fortigateInterfaces.length)return{kind:'table',columns:[...new Set(fortigateInterfaces.flatMap(row=>Object.keys(row)))],items:fortigateInterfaces,summary:{total:fortigateInterfaces.length,up:fortigateInterfaces.filter(row=>row.status!=='down').length,down:fortigateInterfaces.filter(row=>row.status==='down').length}};
 const table=parseDelimitedTable(lines);if(table)return{kind:'table',columns:Object.keys(table[0]),items:table,summary:summarize(table)};const fields=parseKeyValues(lines);if(Object.keys(fields).length>=2||(module==='system'&&Object.keys(fields).length))return{kind:'key-value',fields,summary:{fields:Object.keys(fields).length}};if(device.deviceType==='linux-server'){const os=joined.match(/^PRETTY_NAME=["']?(.+?)["']?$/m)?.[1],kernel=joined.match(/^(Linux\s+[^\n]+)/m)?.[1],load=joined.match(/load average:\s*(.+)$/mi)?.[1],memory=joined.match(/^Mem:\s+(.*)$/mi)?.[1],swap=joined.match(/^Swap:\s+(.*)$/mi)?.[1];return{kind:'key-value',fields:Object.fromEntries([['Operating System',os],['Kernel',kernel],['Load Average',load],['Memory (MB: total used free shared cache available)',memory],['Swap (MB: total used free)',swap]].filter(([,v])=>v)),summary:{lines:lines.length}};}if(STRUCTURED_MODULE.test(module))return{kind:'table',columns:[],items:[],summary:{total:0},parseFailed:true,warnings:[`Parser could not safely normalize ${device.deviceType}:${module}; raw CLI output was suppressed`]};const rawContent = joined || (typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value || ''));
return {
  kind: 'key-value',
  fields: {
    'Raw Output': rawContent,
    'Parser Status': `Raw CLI fallback for ${device.deviceType}:${module}`
  },
  items: [
    {
      'raw_output': rawContent,
      'device': device.deviceType,
      'module': module
    }
  ],
  columns: ['raw_output'],
  summary: { total: 1 },
  parseFailed: false,
  warnings: [`Raw CLI / JSON output for ${device.deviceType}:${module}`]
};}
function normalizeDeviceResponse({device,module,command,data,durationMs,protocol}){const value=unwrap(data),view=Array.isArray(value)||value&&typeof value==='object'?normalizeObjects(value,module):normalizeCli(value,{device,module,command}),lastUpdatedAt=new Date().toISOString(),warnings=view.warnings||[],metadata={deviceId:device.id||null,vendor:device.vendor||device.deviceType,protocol:protocol||device.communicationMethod,durationMs:Number(durationMs||0),lastUpdatedAt,stale:false,parser:view.parser||null,confidence:view.confidence??null};return{capabilityKey:view.capabilityKey||`${device.deviceType}.${module}.list`,entityType:view.entityType||module,items:view.items||[],summary:view.summary||{},facets:{},metadata,warnings,module,view,meta:{protocol:metadata.protocol,durationMs:metadata.durationMs,lastUpdatedAt,partial:Boolean(view.parseFailed),warnings}};}
module.exports={normalizeDeviceResponse,stripCli,normalizeCli,normalizeObjects,summarize,parseHuaweiSystem,parseHuaweiHealth,parseHuaweiPonPorts,parseNokiaPorts,parseFortigateInterfaces,parseTraffic};
